In [139]:
import pandas as pd

train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [141]:
train_df.head(10)

,Ticker,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,ticker_1,1962-01-02,0.000000,0.265828,0.261788,0.261788,25600.0,0.0,0.0
1,ticker_20,1962-01-02,0.000000,0.417455,0.412380,0.414917,84139.0,0.0,0.0
2,ticker_19,1962-01-02,0.000000,0.101537,0.100789,0.100789,902400.0,0.0,0.0
3,ticker_18,1962-01-02,0.000000,0.903030,0.881959,0.881959,51552.0,0.0,0.0
4,ticker_17,1962-01-02,0.130512,0.131783,0.129241,0.130512,163200.0,0.0,0.0
5,ticker_16,1962-01-02,1.574350,1.574350,1.556660,1.556660,407940.0,0.0,0.0
6,ticker_14,1962-01-02,0.000000,0.999724,0.976598,0.976598,5800.0,0.0,0.0
7,ticker_13,1962-01-02,0.190311,0.190311,0.187037,0.187037,352350.0,0.0,0.0
8,ticker_12,1962-01-02,0.000000,1.550548,1.541704,1.541704,55930.0,0.0,0.0
9,ticker_11,1962-01-02,2.609572,2.653065,2.583476,2.600873,432682.0,0.0,0.0

In [143]:
test_df.head(10)

            ID        Date
0     ticker_1  2024-11-04
1    ticker_10  2024-11-04
2   ticker_100  2024-11-04
3  ticker_1000  2024-11-04
4  ticker_1001  2024-11-04
5  ticker_1002  2024-11-04
6  ticker_1003  2024-11-04
7  ticker_1004  2024-11-04
8  ticker_1005  2024-11-04
9  ticker_1006  2024-11-04

In [145]:
train_df.shape

(21033522, 9)

In [147]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21033522 entries, 0 to 21033521
Data columns (total 9 columns):
 #   Column        Dtype
---  ------        -----
 0   Ticker        object
 1   Date          object
 2   Open          float64
 3   High          float64
 4   Low           float64
 5   Close         float64
 6   Volume        float64
 7   Dividends     float64
 8   Stock Splits  float64
dtypes: float64(7), object(2)
memory usage: 1.4+ GB

In [149]:
train_df['Date'] = pd.to_datetime(train_df['Date'])

In [150]:
train_df.describe()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,21033522,2.103352e+07,2.103352e+07,2.103352e+07,2.103352e+07,2.103352e+07,2.103352e+07,21033522.0
mean,2010-07-13 05:38:49.608935168,2.285003e+01,2.335000e+01,2.265493e+01,2.300253e+01,1.174856e+06,2.012335e-03,inf
min,1962-01-02 00:00:00,0.000000e+00,7.606973e-02,0.000000e+00,7.425315e-02,0.000000e+00,0.000000e+00,0.0
25%,2003-06-10 00:00:00,4.680000e+00,4.900000e+00,4.727687e+00,4.810000e+00,2.550000e+04,0.000000e+00,0.0
50%,2013-05-06 00:00:00,1.162689e+01,1.189265e+01,1.151079e+01,1.170101e+01,1.452000e+05,0.000000e+00,0.0
75%,2020-02-27 00:00:00,2.584961e+01,2.627552e+01,2.554281e+01,2.591151e+01,6.881000e+05,0.000000e+00,0.0
max,2024-09-23 00:00:00,8.319200e+02,1.010080e+03,4.320597e+02,4.356200e+02,3.565254e+09,1.594000e+02,inf
std,NaN,3.409086e+01,3.457287e+01,3.360952e+01,3.408867e+01,6.574807e+06,8.486632e-02,NaN

## Feature Engineer

In [154]:
train_df['Ticker'].value_counts()

Ticker
ticker_1       15789
ticker_9       15789
ticker_20      15789
ticker_10      15789
ticker_2       15789
               ...
ticker_4995      232
ticker_4997      231
ticker_4998      229
ticker_4999      225
ticker_5000      224
Name: count, Length: 5000, dtype: int64

In [156]:
# sort by ticker number and date
train_df = train_df.sort_values(['Ticker', 'Date'])

In [157]:
train_df.head()

,Ticker,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,ticker_1,1962-01-02,0.0,0.265828,0.261788,0.261788,25600.0,0.0,0.0
25,ticker_1,1962-01-03,0.0,0.263808,0.261788,0.261788,28800.0,0.0,0.0
49,ticker_1,1962-01-04,0.0,0.263404,0.260980,0.260980,21600.0,0.0,0.0
76,ticker_1,1962-01-05,0.0,0.259364,0.255324,0.255324,46400.0,0.0,0.0
97,ticker_1,1962-01-08,0.0,0.259364,0.255728,0.256536,29600.0,0.0,0.0

In [158]:
train_df.tail()

,Ticker,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
21010467,ticker_999,2024-09-17,87.059998,88.120003,87.059998,87.709999,997900.0,0.0,0.0
21014125,ticker_999,2024-09-18,87.720001,87.959999,86.680000,86.870003,757100.0,0.0,0.0
21019828,ticker_999,2024-09-19,88.220001,89.089996,87.680000,88.800003,885900.0,0.0,0.0
21026462,ticker_999,2024-09-20,89.019997,90.070000,88.610001,89.910004,1665400.0,0.0,0.0
21032385,ticker_999,2024-09-23,90.070000,90.239998,89.480003,89.989998,569600.0,0.0,0.0

In [162]:
# creating the target feature 1 if close after 30 days is higher or 0 if is less
train_df['Target'] = (train_df.groupby('Ticker')['Close'].shift(-30) > train_df['Close']).astype(int)

In [164]:
# creating lag features
train_df['Close_lag_1'] = train_df.groupby('Ticker')['Close'].shift(1)
train_df['Close_lag_7'] = train_df.groupby('Ticker')['Close'].shift(7)

In [165]:
# creating return features
train_df['Return_1'] = train_df.groupby('Ticker')['Close'].pct_change(1)
train_df['Return_7'] = train_df.groupby('Ticker')['Close'].pct_change(7)

In [166]:
# creating SMA feature
train_df['SMA_10'] = train_df.groupby('Ticker')['Close'].transform(lambda x: x.rolling(window=10).mean())
train_df['SMA_30'] = train_df.groupby('Ticker')['Close'].transform(lambda x: x.rolling(window=30).mean())

In [201]:
train_df.head(10)

,Ticker,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Target,Close_lag_1,Close_lag_7,Return_1,Return_7,SMA_10,SMA_30
0,ticker_1,1962-01-02,0.0,0.265828,0.261788,0.261788,25600.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN
25,ticker_1,1962-01-03,0.0,0.263808,0.261788,0.261788,28800.0,0.0,0.0,0,0.261788,NaN,0.000000,NaN,NaN,NaN
49,ticker_1,1962-01-04,0.0,0.263404,0.260980,0.260980,21600.0,0.0,0.0,1,0.261788,NaN,-0.003086,NaN,NaN,NaN
76,ticker_1,1962-01-05,0.0,0.259364,0.255324,0.255324,46400.0,0.0,0.0,1,0.260980,NaN,-0.021673,NaN,NaN,NaN
97,ticker_1,1962-01-08,0.0,0.259364,0.255728,0.256536,29600.0,0.0,0.0,1,0.255324,NaN,0.004747,NaN,NaN,NaN
113,ticker_1,1962-01-09,0.0,0.259364,0.256132,0.256132,40000.0,0.0,0.0,1,0.256536,NaN,-0.001575,NaN,NaN,NaN
129,ticker_1,1962-01-10,0.0,0.257748,0.242396,0.255324,20800.0,0.0,0.0,1,0.256132,NaN,-0.003155,NaN,NaN,NaN
144,ticker_1,1962-01-11,0.0,0.257748,0.255728,0.256536,25600.0,0.0,0.0,0,0.255324,0.261788,0.004747,-0.020062,NaN,NaN
171,ticker_1,1962-01-12,0.0,0.259364,0.256132,0.258556,16000.0,0.0,0.0,0,0.256536,0.261788,0.007874,-0.012346,NaN,NaN
198,ticker_1,1962-01-15,0.0,0.259364,0.257748,0.259364,34400.0,0.0,0.0,0,0.258556,0.260980,0.003125,-0.006193,0.258232,NaN

In [199]:
train_df.tail()

,Ticker,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Target,Close_lag_1,Close_lag_7,Return_1,Return_7,SMA_10,SMA_30
21010467,ticker_999,2024-09-17,87.059998,88.120003,87.059998,87.709999,997900.0,0.0,0.0,0,86.879997,82.330002,0.009553,0.065347,84.388999,84.112333
21014125,ticker_999,2024-09-18,87.720001,87.959999,86.680000,86.870003,757100.0,0.0,0.0,0,87.709999,83.019997,-0.009577,0.046374,84.770999,84.309666
21019828,ticker_999,2024-09-19,88.220001,89.089996,87.680000,88.800003,885900.0,0.0,0.0,0,86.870003,82.889999,0.022217,0.071299,85.353999,84.596000
21026462,ticker_999,2024-09-20,89.019997,90.070000,88.610001,89.910004,1665400.0,0.0,0.0,0,88.800003,84.349998,0.012500,0.065916,86.112000,84.882667
21032385,ticker_999,2024-09-23,90.070000,90.239998,89.480003,89.989998,569600.0,0.0,0.0,0,89.910004,85.129997,0.000890,0.057089,86.809000,85.163667

In [172]:
# dropping nan rows
fit_train = train_df.dropna()

In [173]:
fit_train.head()

,Ticker,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Target,Close_lag_1,Close_lag_7,Return_1,Return_7,SMA_10,SMA_30
595,ticker_1,1962-02-12,0.0,0.251320,0.250096,0.251320,22400.0,0.0,0.0,1,0.251320,0.251320,0.000000,0.000000,0.251156,0.253733
614,ticker_1,1962-02-13,0.0,0.256216,0.250912,0.254992,36000.0,0.0,0.0,1,0.251320,0.251320,0.014611,0.014611,0.251524,0.253506
639,ticker_1,1962-02-14,0.0,0.258663,0.255807,0.258663,41600.0,0.0,0.0,1,0.254992,0.251320,0.014400,0.029220,0.252340,0.253402
640,ticker_1,1962-02-15,0.0,0.261927,0.258663,0.261927,38400.0,0.0,0.0,1,0.258663,0.250912,0.012619,0.043902,0.253400,0.253434
668,ticker_1,1962-02-16,0.0,0.261927,0.257848,0.258256,38400.0,0.0,0.0,1,0.261927,0.252136,-0.014018,0.024273,0.254094,0.253531

## Model Training

In [177]:
from sklearn.model_selection import train_test_split

# data spliting
x =  train_fit[['Close_lag_1', 'Close_lag_7', 'Return_1', 'Return_7', 'SMA_10', 'SMA_30']]
y = train_fit['Target']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(f"Size of training data: {x_train.shape[0]}")
print(f"Size of test data: {x_test.shape[0]}")

Size of training data: 16710817
Size of test data: 4177705

In [179]:
from sklearn.ensemble import RandomForestClassifier

# random forest classifier
rf = RandomForestClassifier(n_estimators=50, max_depth=10)
rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=50)

In [239]:
y_pred = rf.predict(x_test)

In [241]:
from sklearn.metrics import accuracy_score, classification_report

# accuracy score
print(f"Accuracy score of Random Forest Classifier: {accuracy_score(y_test, y_pred)}")

# classification report
target_names = ['Lower', 'Higher']
print(classification_report(y_test, y_pred, target_names=target_names))

Accuracy score of Random Forest Classifier: 0.5420133781585823
              precision    recall  f1-score   support

       Lower       0.53      0.11      0.19   1938937
      Higher       0.54      0.91      0.68   2238768

    accuracy                           0.54   4177705
   macro avg       0.54      0.51      0.43   4177705
weighted avg       0.54      0.54      0.45   4177705

## Test Data

In [203]:
# create features for test data
## combine both datasets
combine_df = pd.concat([train_df[['Ticker', 'Date', 'Close']], test_df.rename(columns={'ID':'Ticker'})[['Ticker', 'Date']]],ignore_index=True, sort=False)

In [205]:
combine_df.head()

     Ticker                 Date     Close
0  ticker_1  1962-01-02 00:00:00  0.261788
1  ticker_1  1962-01-03 00:00:00  0.261788
2  ticker_1  1962-01-04 00:00:00  0.260980
3  ticker_1  1962-01-05 00:00:00  0.255324
4  ticker_1  1962-01-08 00:00:00  0.256536

In [207]:
# creatins features used for train the model
## creating lag features
combine_df['Close_lag_1'] = combine_df.groupby('Ticker')['Close'].shift(1)
combine_df['Close_lag_7'] = combine_df.groupby('Ticker')['Close'].shift(7)

## creating return features
combine_df['Return_1'] = combine_df.groupby('Ticker')['Close'].pct_change(1)
combine_df['Return_7'] = combine_df.groupby('Ticker')['Close'].pct_change(7)

## creating SMA feature
combine_df['SMA_10'] = combine_df.groupby('Ticker')['Close'].transform(lambda x: x.rolling(window=10, min_periods=1).mean())
combine_df['SMA_30'] = combine_df.groupby('Ticker')['Close'].transform(lambda x: x.rolling(window=30, min_periods=1).mean())

C:\Users\car_f\AppData\Local\Temp\ipykernel_17084\1734671667.py:7: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  combine_df['Return_1'] = combine_df.groupby('Ticker')['Close'].pct_change(1)
C:\Users\car_f\AppData\Local\Temp\ipykernel_17084\1734671667.py:8: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  combine_df['Return_7'] = combine_df.groupby('Ticker')['Close'].pct_change(7)

In [209]:
combine_df['Date'] = pd.to_datetime(combine_df['Date'])

In [211]:
combine_df.head(10)

,Ticker,Date,Close,Close_lag_1,Close_lag_7,Return_1,Return_7,SMA_10,SMA_30
0,ticker_1,1962-01-02,0.261788,NaN,NaN,NaN,NaN,0.261788,0.261788
1,ticker_1,1962-01-03,0.261788,0.261788,NaN,0.000000,NaN,0.261788,0.261788
2,ticker_1,1962-01-04,0.260980,0.261788,NaN,-0.003086,NaN,0.261518,0.261518
3,ticker_1,1962-01-05,0.255324,0.260980,NaN,-0.021673,NaN,0.259970,0.259970
4,ticker_1,1962-01-08,0.256536,0.255324,NaN,0.004747,NaN,0.259283,0.259283
5,ticker_1,1962-01-09,0.256132,0.256536,NaN,-0.001575,NaN,0.258758,0.258758
6,ticker_1,1962-01-10,0.255324,0.256132,NaN,-0.003155,NaN,0.258267,0.258267
7,ticker_1,1962-01-11,0.256536,0.255324,0.261788,0.004747,-0.020062,0.258051,0.258051
8,ticker_1,1962-01-12,0.258556,0.256536,0.261788,0.007874,-0.012346,0.258107,0.258107
9,ticker_1,1962-01-15,0.259364,0.258556,0.260980,0.003125,-0.006193,0.258232,0.258232

In [213]:
# getting the features of the date 2024-11-04
date_test = combine_df[combine_df['Date'] == '2024-11-04']

In [217]:
date_test.head()

,Ticker,Date,Close,Close_lag_1,Close_lag_7,Return_1,Return_7,SMA_10,SMA_30
21033522,ticker_1,2024-11-04,NaN,104.019997,104.559998,0.0,-0.005165,103.784444,102.270344
21033523,ticker_10,2024-11-04,NaN,173.770004,174.080002,0.0,-0.001781,174.226668,172.200344
21033524,ticker_100,2024-11-04,NaN,256.649994,251.750000,0.0,0.019464,253.191111,247.909311
21033525,ticker_1000,2024-11-04,NaN,52.980000,52.380001,0.0,0.011455,52.332222,52.180345
21033526,ticker_1001,2024-11-04,NaN,20.290001,20.559999,0.0,-0.013132,20.254444,20.306552

In [223]:
# predict 
x_test_pred = date_test[['Close_lag_1', 'Close_lag_7', 'Return_1', 'Return_7', 'SMA_10', 'SMA_30']]
predict = rf.predict(x_test_pred)

In [228]:
submission = pd.DataFrame({
    'ID': date_test['Ticker'],
    'Pred': predict
})

submission.to_csv('submission.csv', index=False)